/**
 * `stereoframe evaluate` — a deterministic evidence bundle for generated or
 * production GLBs. It does not try to hide model defects with a cinematic preset:
 * it inspects, scores, compares, and stages assets under one standardized rig.
 */
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { basename, extname, join, resolve } from "node:path";
import { inspectModel, type ModelManifest } from "./inspect";
import { buildQualityReport, type QualityReport, type QualityWarning } from "./quality";
import { resolveRuntimeBundle } from "./scaffold";
import { captureFrame, type FrameResult } from "./frame";
import { renderProject } from "./render";

export interface EvaluationAsset {
  label: string;
  source: string;
  asset: string;
  report: string;
  score: number;
  manifest: ModelManifest;
  quality: QualityReport;
}

export interface EvaluationSummary {
  generatedBy: "stereoframe evaluate";
  title: string;
  createdAt: string;
  assets: Array<{
    label: string;
    source: string;
    asset: string;
    report: string;
    score: number;
    warnings: string[];
    metrics: QualityReport["metrics"];
  }>;
}

export interface EvaluateOptions {
  models: string[];
  outDir: string;
  title?: string;
  frames?: number[];
  render?: boolean;
  draft?: boolean;
}

export interface EvaluateResult {
  dir: string;
  index: string;
  report: string;
  summary: string;
  frames: FrameResult[];
  render?: string;
  assets: EvaluationAsset[];
}

function slugify(input: string): string {
  return (
    input
      .toLowerCase()
      .replace(/\.(glb|gltf)$/i, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "model"
  );
}

function uniqueAssetName(path: string, seen: Map<string, number>): string {
  const ext = extname(path).toLowerCase() || ".glb";
  const base = slugify(basename(path));
  const count = seen.get(base) ?? 0;
  seen.set(base, count + 1);
  return `${base}${count ? `-${count + 1}` : ""}${ext}`;
}

function escapeHtml(input: string): string {
  return input.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function qualityScore(warnings: QualityWarning[]): number {
  const weights: Record<QualityWarning["code"], number> = {
    thin_flat: 18,
    extreme_aspect: 12,
    single_mesh: 15,
    high_poly: 10,
    low_geometry: 30,
    off_origin: 12,
  };
  const penalty = warnings.reduce((sum, w) => sum + weights[w.code], 0);
  return Math.max(0, Math.min(100, 100 - penalty));
}

function labelForModel(path: string): string {
  return basename(path).replace(/\.(glb|gltf)$/i, "");
}

function buildSummary(title: string, assets: EvaluationAsset[]): EvaluationSummary {
  return {
    generatedBy: "stereoframe evaluate",
    title,
    createdAt: new Date().toISOString(),
    assets: assets.map((asset) => ({
      label: asset.label,
      source: asset.source,
      asset: asset.asset,
      report: asset.report,
      score: asset.score,
      warnings: asset.quality.warnings.map((w) => w.code),
      metrics: asset.quality.metrics,
    })),
  };
}

export function buildEvaluationMarkdown(summary: EvaluationSummary): string {
  const lines = [
    `# ${summary.title}`,
    "",
    "Deterministic GLB evaluation bundle generated by `stereoframe evaluate`.",
    "",
    "| Asset | Score | Warnings | Triangles | Parts | Bounds | Material |",
    "|---|---:|---|---:|---:|---|---|",
  ];
  for (const asset of summary.assets) {
    const metrics = asset.metrics;
    const bounds = metrics.boundsSize.map((n) => Number(n).toFixed(2)).join(" x ");
    lines.push(
      `| ${asset.label} | ${asset.score} | ${asset.warnings.join(", ") || "none"} | ${metrics.totalTriangles} | ${metrics.partCount} | ${bounds} | ${metrics.dominantMaterial} |`,
    );
  }
  lines.push(
    "",
    "## Outputs",
    "",
    "- `index.html` — standardized side-by-side preview composition.",
    "- `reports/summary.json` — machine-readable metrics, warnings, and scores.",
    "- `reports/*.quality.json` — per-asset quality reports.",
    "- `frames/` — optional standardized frame captures when `--frames` is used.",
    "- `renders/evaluation.mp4` — optional preview render when `--render` is used.",
    "",
    "Scores are heuristic evidence, not a claim of visual quality. Inspect the frames/video before accepting an asset.",
    "",
  );
  return `${lines.join("\n")}\n`;
}

export function buildEvaluationHtml(title: string, assets: EvaluationAsset[]): string {
  const count = assets.length;
  const spacing = count <= 1 ? 0 : count === 2 ? 3.1 : count === 3 ? 2.45 : 2.0;
  const fit = count <= 1 ? 2.6 : count === 2 ? 2.15 : count === 3 ? 1.75 : 1.45;
  const x0 = -((count - 1) * spacing) / 2;
  const models = assets
    .map((asset, i) => {
      const x = x0 + i * spacing;
      return `      <sf-model id="m${i + 1}" src="${asset.asset}" fit="${fit}" fit-ground position="${x.toFixed(2)} 0 0"></sf-model>
      <sf-animate target="#m${i + 1}" verb="turntable" rpm="3"></sf-animate>
      <sf-animate target="#m${i + 1}" verb="sway" amount="0.25" period="7"></sf-animate>`;
    })
    .join("\n");
  const labels = assets
    .map((asset) => {
      const warnings = asset.quality.warnings.map((w) => w.code).join(", ") || "no warnings";
      return `      <div class="asset">
        <div class="name">${escapeHtml(asset.label)}</div>
        <div class="score">${asset.score}</div>
        <div class="meta">${escapeHtml(warnings)}</div>
      </div>`;
    })
    .join("\n");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { width: 1920px; height: 1080px; overflow: hidden; background: #08090c; }
      body { font-family: "Helvetica Neue", Arial, sans-serif; color: #f7f7f2; }
      sf-scene { position: absolute; inset: 0; }
      .hud { position: absolute; left: 70px; right: 70px; top: 48px; display: flex; align-items: baseline; justify-content: space-between; pointer-events: none; }
      .title { font-size: 30px; font-weight: 750; letter-spacing: 0.08em; text-transform: uppercase; }
      .stamp { font-size: 14px; letter-spacing: 0.26em; text-transform: uppercase; color: #8ea6bd; }
      .labels { position: absolute; left: 70px; right: 70px; bottom: 48px; display: grid; grid-template-columns: repeat(${count}, minmax(0, 1fr)); gap: 16px; pointer-events: none; }
      .asset { min-height: 112px; border-top: 1px solid rgba(255,255,255,0.22); padding-top: 14px; background: linear-gradient(180deg, rgba(255,255,255,0.055), rgba(255,255,255,0)); }
      .name { font-size: 18px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
      .score { margin-top: 9px; font-size: 42px; font-weight: 800; line-height: 1; color: #f4f7fb; }
      .meta { margin-top: 8px; font-size: 13px; letter-spacing: 0.12em; text-transform: uppercase; color: #8fd0ff; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    </style>
  </head>
  <body>
    <sf-scene duration="8" width="1920" height="1080" background="#08090c"
              environment="room" exposure="0.92" samples="2" bloom="0.08"
              bloom-threshold="0.9" vignette="0.24" contrast="1.07" saturation="1.02"
              grain="0.01" chromatic-aberration="0.035" ground="contact-shadow"
              ground-y="0" ground-size="7" light-sweep="0.05">
      <sf-camera fov="36" position="0 1.18 6.2" look-at="0 0.9 0"></sf-camera>
      <sf-light type="hemisphere" color="#263041" intensity="0.45"></sf-light>
      <sf-light type="directional" color="#ffffff" intensity="1.8" position="4 5 5"></sf-light>
      <sf-light type="directional" color="#8fc8ff" intensity="1.5" position="-5 3 -4"></sf-light>
      <sf-mesh geometry="plane" args="64 64" rotation="-90 0 0" position="0 -0.01 0"
               color="#111318" metalness="0.25" roughness="0.55"></sf-mesh>
${models}
      <sf-animate target="camera" verb="orbit" around="0 0.9 0" radius="6.2"
                  from="-10deg" to="10deg" height="1.18" start="0" duration="8"
                  ease="sine.inOut"></sf-animate>
    </sf-scene>

    <div class="hud">
      <div class="title">${escapeHtml(title)}</div>
      <div class="stamp">standard rig / comparable evidence</div>
    </div>
    <div class="labels">
${labels}
    </div>

    <script type="module">
      import "./assets/stereoframe.js";
    </script>
  </body>
</html>
`;
}

export async function evaluateModels(opts: EvaluateOptions): Promise<EvaluateResult> {
  if (opts.models.length === 0) throw new Error("evaluate needs at least one GLB");
  if (opts.models.length > 4) throw new Error("evaluate supports 1-4 GLBs per comparison suite");

  const dir = resolve(opts.outDir);
  const assetsDir = join(dir, "assets");
  const reportsDir = join(dir, "reports");
  mkdirSync(assetsDir, { recursive: true });
  mkdirSync(reportsDir, { recursive: true });
  copyFileSync(resolveRuntimeBundle(), join(assetsDir, "stereoframe.js"));

  const seen = new Map<string, number>();
  const assets: EvaluationAsset[] = [];
  for (const model of opts.models) {
    const source = resolve(model);
    if (!existsSync(source)) throw new Error(`model not found: ${source}`);
    const assetName = uniqueAssetName(source, seen);
    const assetRel = `assets/${assetName}`;
    copyFileSync(source, join(dir, assetRel));

    const manifest = await inspectModel({ model: source, silent: true, write: false });
    const quality = buildQualityReport(manifest);
    quality.generatedBy = "stereoframe evaluate";
    const reportRel = `reports/${assetName.replace(/\.(glb|gltf)$/i, ".quality.json")}`;
    writeFileSync(join(dir, reportRel), JSON.stringify(quality, null, 2) + "\n");
    assets.push({
      label: labelForModel(source),
      source,
      asset: assetRel,
      report: reportRel,
      score: qualityScore(quality.warnings),
      manifest,
      quality,
    });
  }

  const title = opts.title ?? "GLB Evaluation";
  const summary = buildSummary(title, assets);
  const summaryPath = join(reportsDir, "summary.json");
  const reportPath = join(dir, "REPORT.md");
  const indexPath = join(dir, "index.html");
  writeFileSync(summaryPath, JSON.stringify(summary, null, 2) + "\n");
  writeFileSync(reportPath, buildEvaluationMarkdown(summary));
  writeFileSync(indexPath, buildEvaluationHtml(title, assets));
  writeFileSync(join(dir, ".gitignore"), "renders/\nframes/\n");

  const frames: FrameResult[] = [];
  for (const t of opts.frames ?? []) {
    const safe = String(t).replace(/[^0-9.]+/g, "_");
    frames.push(await captureFrame({ projectDir: dir, t, out: `frames/eval_${safe}s.png` }));
  }
  const render = opts.render
    ? await renderProject({ projectDir: dir, out: "renders/evaluation.mp4", draft: opts.draft })
    : undefined;

  return { dir, index: indexPath, report: reportPath, summary: summaryPath, frames, render, assets };
}
